"use client"
import { useContext, useEffect } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { isThemeMode } from '@/utils/storage/theme'
import { ThemeProvider } from './components/context/Theme/useTheme'
import { NavigationContext, NavigationProvider } from './components/context/Navigation/useNavigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { } = useContext(NavigationContext)

  return (
    <ThemeProvider>
      <html lang="en" >
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>

  )
}
